name: Build and publish Docker distributions to Github Container Registry ghcr.io

on:
  push:
    branches:
    - master
    - version-*
    paths:
    - gradle.properties

jobs:
  sonatype-job:
    uses: th2-net/.github/.github/workflows/java-publish-sonatype.yml@th2-4253-jar-publishing
    secrets:
      SONATYPE_NEXUS_USERNAME: ${{ secrets.SONATYPE_NEXUS_USERNAME }}
      SONATYPE_NEXUS_PASSWORD: ${{ secrets.SONATYPE_NEXUS_PASSWORD }}
      SONATYPE_GPG_ARMORED_KEY: ${{ secrets.SONATYPE_GPG_ARMORED_KEY }}
      SONATYPE_SIGNING_PASSWORD: ${{ secrets.SONATYPE_SIGNING_PASSWORD }}
  owasp-scan:
    uses: th2-net/.github/.github/workflows/owasp-gradle-scan.yml@main
